# fly.toml app configuration file generated for server-yoga-app on 2023-08-25T08:34:24-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-yoga-app"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
